### ISSUE TITLE
Failed building wheel

### ISSUE THREAD

**Issue by pskugit** [gatagat/lap#18]
When trying to install via pip or from source I am not able to build lap.
Do you have an idea what I might be missing?
I did install the listed prerequisites.

I'm on linux and my problem seems similar to #13 
ERROR: failed building wheel for lap

**Comment by gatagat** [comment]
Please provide the log or at least the error message.

But ff the error log is similar as in #13, it could be a similar cause;) Do you have a compiler installed?

**Comment by pskugit** [comment]
log was pretty similar as #13.. It somehow ended up working with pip3 and a new virtual environment. Nothing changed on the compiler though. 
Not sure about how everything interacts, but I got it running, thanks.

**Comment by gatagat** [comment]
Cool, thanks for letting us now.
