### ISSUE TITLE
Please release 0.5.0 to PyPI

### ISSUE THREAD

**Issue by remram44** [gatagat/lap#34]
There were some changes in 2019 that is not available on PyPI, it would be great if you could make a new release. Thanks!

edit: Published as [lap05](https://pypi.org/project/lap05/)

**Comment by remram44** [comment]
@gatagat respectfully bumping

**Comment by gatagat** [comment]
@remram44 Really sorry for the almost eternal silence... A new updated version 0.5.12 of lap is now available on PyPI.
