### ISSUE TITLE
Remove deprecated LooseVersion from distutils

### ISSUE THREAD

**Issue by gatagat** [gatagat/lap#36]
This particular usage of distutils concerns the install (setup.py):

```
setup.py:87: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if LooseVersion(cython_version) < LooseVersion('0.21'):
```

Either bundle some solution a la [scipy._lib._pep440](https://github.com/scipy/scipy/pull/15256) or switch to the [packaging package](pypi.org/project/packaging/) using `packaging.version.Version`.

**Comment by rathaROG** [comment]
Maybe we can close this, right? @gatagat

**Comment by gatagat** [comment]
Totally.
