### ISSUE TITLE
ERROR: Command errored out with exit status 1:

### ISSUE THREAD

**Issue by blizaga** [gatagat/lap#49]
I found the issue of not being able to install the package because of errors like the following

ERROR: Command errored out with exit status 1: /home/fariz/anaconda3/envs/sort/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nisky4s6/lap_6f39d61b6085428aaa64a8b21ff4f597/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nisky4s6/lap_6f39d61b6085428aaa64a8b21ff4f597/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-trd_3n3z/install-record.txt --single-version-externally-managed --compile --install-headers /home/fariz/anaconda3/envs/sort/include/python3.6m/lap Check the logs for full command output.

![image](https://github.com/gatagat/lap/assets/54091450/eda49497-c16c-47b4-992d-ad3d767606c4)

**Comment by gatagat** [comment]
Lap does not support Python 3.6 anymore, please try using at least 3.7.
