### ISSUE TITLE
No issue -> `lapx` is live on PyPI for all Windows/Linux/macOS Python 3.7-3.12

### ISSUE THREAD

**Issue by rathaROG** [gatagat/lap#50]
Hi, 

I don't know if it's helpful.. I have some prebuilt whl files for both Windows and Linux with choices of Python 3.9/3.10/3.11 on my repo here ~~[`lap07`](https://github.com/rathaROG/lap07)~~ [`lapx`](https://github.com/rathaROG/lapx). These whl files are built by GitHub action workflow directly..  

Anyway all credit to @gatagat !

Edit:  Better use [`lapx`](https://github.com/rathaROG/lapx) for simpler and cleaner modern [`setup.py`](https://github.com/rathaROG/lapx/blob/main/setup.py) :)

**Comment by rathaROG** [comment]
> @rathaROG Thank you so much, it does help me

Thanks! I'm glad to hear that from you.

I've just updated my workflow actions and shared the prebuilt wheels for all latest Windows/Linux/macOS + Python 3.8/3.9/3.10/3/11 in releases:
https://github.com/rathaROG/lapx/releases/tag/v0.5.1

**Comment by Chrd26** [comment]
Thanks! It works great on MacOS Ventura 13.3.1.

**Comment by gatagat** [comment]
Hi @rathaROG, kudos for stepping in and pushing out lapx! I have now some time to spare and would like to figure out what's the best way forward. Would you be ok if I integrate the changes you did? I'd be also happy to add you to lap and collaborate. Let me know.

**Comment by rathaROG** [comment]
> Hi @rathaROG, kudos for stepping in and pushing out lapx! I have now some time to spare and would like to figure out what's the best way forward. Would you be ok if I integrate the changes you did? I'd be also happy to add you to lap and collaborate. Let me know.

Hello @gatagat I have no problem with that and I'm glad you're back.

**Comment by gatagat** [comment]
Cool! I try applying your commits from lapx then.

**Comment by gatagat** [comment]
The changes from lapx and lap 0.5.12  to continue with the version numbers of lapx. New lap with all the changes is available on PyPI now.

@rathaROG I've added you to lap as a collaborator.

**Comment by rathaROG** [comment]
> The changes from lapx are applied and there's a new version of lap 0.5.12 available on PyPI.
> 
> @rathaROG I've added you to lap as a collaborator.

Thanks, I didn't expect your invitation and all of this. I will contribute what I can do in the future.
