### ISSUE TITLE
WineBottler 4.0.1.1 cannot open exe file on Mac 2023

### ISSUE THREAD

**Issue by truongkhaihoa1995** [gatagat/lap#55]
###BOTTLING### customprefix.sh
/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Frameworks/WBottler.framework/Resources/bottler.sh: line 39: /private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources/bin/wine: Bad CPU type in executable
###BOTTLING### Gathering debug Info...

Versions
OS...........................: darwin23
Wine.........................: 
WineBottler..................: 1.8.6
Wineticks....................: 20230212-next - sha256sum: fe0550e0d843214f87dcb0f4aa591be0046fa93db7b8330217dd926258e628fc

Environment
PWD..........................: '/private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources/bin'
PATH.........................: /private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources/bin:/usr/bin:/bin:/usr/sbin:/sbin
USER.........................: hoatruong
HOME.........................: /Users/hoatruong
COMPUTERNAME.................: Hoaâs MacBook Pro
BUNDLERESOURCEPATH...........: /var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Frameworks/WBottler.framework/Resources
WINEPREFIX...................: /private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources
WINEPATH.....................: /private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources/bin
LD_LIBRARY_PATH..............: /private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources/lib:/opt/X11/lib:/usr/X11/lib
DYLD_FALLBACK_LIBRARY_PATH...: /private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources/lib:/usr/lib:/opt/X11/lib:/usr/X11/lib
SILENT.......................: 
http_proxy...................: 
https_proxy..................: 
ftp_proxy....................: 
socks5_proxy.................: 

Bottle
TEMPLATE.....................: 
BOTTLE.......................: /Users/hoatruong/Wine Files
INSTALLER_URL................: 
INSTALLER_IS_ZIPPED..........: 0
INSTALLER_NAME...............: 
INSTALLER_ARGUMENTS..........: 
REMOVE_MONO..................: 
REMOVE_GECKO.................: 
REMOVE_USERS.................: 
REMOVE_INSTALLERS............: 
WINETRICKS_ITEMS.............: 
DLL_OVERRIDES................: 
EXECUTABLE_PATH..............: notneeded
EXECUTABLE_ARGUMENTS.........: 
EXECUTABLE_VERSION...........: 1.0.0
BUNDLE_COPYRIGHT.............: 
BUNDLE_IDENTIFIER............: org.kronenberg.winebottler
BUNDLE_CATEGORYTYPE..........: public.app-category.utilities
SILENT.......................: 

Hardware:

    Hardware Overview:

      Model Name: Mac
      Model Identifier: Mac14,9
      Model Number: MPHE3LL/A
      Chip: Unknown
      Total Number of Cores: 10 (6 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 10151.41.12
      OS Loader Version: 10151.41.12
      Serial Number (system): J2CPX1QJRR
      Hardware UUID: 69307717-45AF-5F6A-8767-BC95CC022E04
      Provisioning UDID: 69307717-45AF-5F6A-8767-BC95CC022E04
      Activation Lock Status: Disabled

###BOTTLING### Enabling CoreAudio, Colors, Antialiasing  and flat menus...
/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Frameworks/WBottler.framework/Resources/bottler.sh: line 134: /private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources/bin/wine: Bad CPU type in executable
### LOG ### Command '/private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources/bin/wine regedit /tmp/reg.reg' returned status 126.

###ERROR### Command '/private/var/folders/xk/tdz2k3tn02nfp3fyw2g32db40000gn/T/AppTranslocation/EAAE4D22-F489-4DD0-A4F3-FD69B28EFE6B/d/Wine.app/Contents/Resources/bin/wine regedit /tmp/reg.reg' returned status 126.
Task returned with status 1.

**Comment by gatagat** [comment]
Hi @truongkhaihoa1995, this does not seem relevant for lap. If you are sure this is an issue against lap, please provide more information. Until then let me close this issue.
