### ISSUE TITLE
problem installing LAP library in vscode using pyhton 3.12.4

### ISSUE THREAD

**Issue by AjayKadam1** [gatagat/lap#59]
(myenv) C:\Python_ML\Project>pip install lap
Collecting lap
  Using cached lap-0.4.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: lap
  Building wheel for lap (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      C:\Users\AjayK\AppData\Local\Temp\pip-install-76bfr7uy\lap_db498f4eb29b4e47a19c425b5b8f640f\setup.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Partial import of lap during the build process.
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\AjayK\AppData\Local\Temp\pip-install-76bfr7uy\lap_db498f4eb29b4e47a19c425b5b8f640f\setup.py", line 236, in <module> 
          setup_package()
        File "C:\Users\AjayK\AppData\Local\Temp\pip-install-76bfr7uy\lap_db498f4eb29b4e47a19c425b5b8f640f\setup.py", line 223, in setup_package
          from numpy.distutils.core import setup
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lap
  Running setup.py clean for lap
Failed to build lap
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (lap)

**Comment by inam1611** [comment]
Same issue occuring with my setup

**Comment by raphaelreme** [comment]
Hey,

I believe that this should solve your issues: https://github.com/rathaROG/lapx. (you can just pip install lapx instead of pip install lap, and everything will work as before)

**Comment by gatagat** [comment]
Hi @raphaelreme and others, lap is back! After talking with rathaROG, I could use most of his changes and publish [lap 0.5.12 on PyPI](https://pypi.org/project/lap/#files). The plan is to work on lap together 🚀
